const FACE_DOWN_UNICODE = "\u{1F0A0}";
const PLACE_PILE = "pile";
const PLACE_WASTE_PILE = "waste-pile";
const PLACE_FOUNDATION = "foundation";

export { FACE_DOWN_UNICODE, PLACE_FOUNDATION, PLACE_PILE, PLACE_WASTE_PILE}